#!/bin/bash

# bash
ln -sf /home/$USER/config/.bashrc /home/$USER/

# vim
ln -sf /home/$USER/config/.vimrc /home/$USER/

# tmux
ln -sf /home/$USER/config/.tmux.conf /home/$USER/

# conda
ln -sf /home/$USER/config/.condarc /home/$USER/

# alacritty
ln -sf /home/$USER/config/.alacritty.yml /home/$USER

# xmonad
ln -sf /home/$USER/config/.xmonad /home/$USER

# xmobar
ln -sf /home/$USER/config/.xmobar /home/$USER
